spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_adminlte?createDatabaseIfNotExist=true
    username: root
    password: 123
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    database: MYSQL
    show: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: file:./src/main/resources/templates/
#  session.store-type: none
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
liquibase:
  change-log: classpath:db/liquibase-changelog.xml