spring:
  application:
    name: hbp-card-portal
  datasource:
    db: hbp-card-portal
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    host: localhost
    port: 1433
#    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db}?createDatabaseIfNotExist=true
    url: jdbc:sqlserver://${spring.datasource.host}:${spring.datasource.port};databaseName=${spring.datasource.db};createDatabaseIfNotExist=true;useUnicod=true
#    username: root
    username: sa
    password: Password1
    tomcat:
      initial-size: 6
      max-wait: 20000
      max-active: 100
      max-idle: 10
      min-idle: 4
      validation-query-timeout: 2
      initialize: false
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    database: SQL_SERVER
    show: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: file:./src/main/resources/templates/
  session:
    store-type: jdbc
#    jdbc:
#      initialize-schema: embedded
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
server:
  servlet:
    session:
      cookie:
        http-only: true
#        secure: true
      timeout: 120m
  tomcat:
    accesslog:
      max-logs: 10
      enabled: true
      directory: ./
    basedir: logs
logging:
  file: logs/app.log
  file.name: logs/application-spring.log
  file.path: /var/log
  file.max-history: 3
  file.max-size: 1MB